services:
  - type: web
    name: MedGPT-AI
    env: python
    plan: free
    runtime: python-3.11.9
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
